# Generated by Django 2.1.1 on 2018-12-07 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=1)),
                ('is_superuser', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisementID', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.IntegerField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.IntegerField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('permissionTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('propertyID', models.AutoField(primary_key=True, serialize=False)),
                ('propertyTitle', models.CharField(max_length=50)),
                ('propertyStreet', models.TextField()),
                ('propertyPostalCode', models.CharField(max_length=10)),
                ('propertyStreetNumber', models.CharField(max_length=20)),
                ('propertyConstructionDate', models.DateField()),
                ('propertyRegistrationDate', models.DateField()),
                ('propertyNumberOfHalls', models.IntegerField()),
                ('propertyNumberOfRooms', models.IntegerField()),
                ('propertyNoofBathrooms', models.IntegerField()),
                ('propertyNoofFloors', models.IntegerField()),
                ('propertyTotalArea', models.FloatField()),
                ('propertyAskingPrice', models.FloatField()),
                ('propertySellingPrice', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('PropertyCategoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyFacing',
            fields=[
                ('PropertyFacingId', models.IntegerField(primary_key=True, serialize=False)),
                ('PropertyFacingName', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('ImageName', models.ImageField(blank=True, null=True, upload_to='')),
                ('propertyImageID', models.IntegerField(primary_key=True, serialize=False)),
                ('propertyImageDescription', models.TextField()),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertySector',
            fields=[
                ('PropertySectorId', models.IntegerField(primary_key=True, serialize=False)),
                ('SectorName', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provinceID', models.IntegerField(primary_key=True, serialize=False)),
                ('provinceName', models.CharField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleCode',
            fields=[
                ('roleCodeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('rolePermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('dateAssigned', models.DateField(default=datetime.date.today)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.RoleCode')),
                ('permissionTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PermissionType')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('dateAssigned', models.DateField(default=datetime.date.today)),
                ('roleCodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.RoleCode')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rolecode',
            name='users',
            field=models.ManyToManyField(through='eproperty.UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eproperty.PropertyCategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eproperty.City'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eproperty.Country'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyFacing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eproperty.PropertyFacing'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyProvince',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eproperty.Province'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertySector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eproperty.PropertySector'),
        ),
        migrations.AddField(
            model_name='property',
            name='users',
            field=models.ManyToManyField(through='eproperty.Advertisement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiontype',
            name='permissions',
            field=models.ManyToManyField(through='eproperty.RolePermission', to='eproperty.RoleCode'),
        ),
        migrations.AddField(
            model_name='city',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Province'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Property'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
