# Generated by Django 2.1.1 on 2018-12-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0003_auto_20181209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
