# Generated by Django 2.1.1 on 2018-12-10 01:02

from django.db import migrations
import eproperty.models


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0004_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', eproperty.models.CustomUserManager()),
            ],
        ),
    ]
