# Generated by Django 2.1.1 on 2018-12-10 03:03

from django.db import migrations, models
import eproperty.managers.manager


class Migration(migrations.Migration):

    dependencies = [
        ('eproperty', '0006_auto_20181209_2016'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', eproperty.managers.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
